import { ApolloClient, InMemoryCache } from '@apollo/client';
import { SchemaLink } from '@apollo/client/link/schema';
import { makeExecutableSchema } from '@graphql-tools/schema';

const typeDefs = `
  type Patient {
    patientID: String!
    name: String!
    age: Int!
    gender: String!
    diagnosis: String!
    status: String!
    doctor: String!
    department: String!
    admissionDate: String!
    dischargeDate: String
  }

  type Query {
    patients: [Patient!]!
  }
`;

const patients = [
  {
    patientID: 'PAT-001',
    name: 'John Doe',
    age: 45,
    gender: 'Male',
    diagnosis: 'Hypertension',
    status: 'admitted',
    doctor: 'Dr. Smith',
    department: 'Cardiology',
    admissionDate: '15/05/2024',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-002',
    name: 'Jane Smith',
    age: 32,
    gender: 'Female',
    diagnosis: 'Asthma',
    status: 'discharged',
    doctor: 'Dr. Johnson',
    department: 'Pulmonology',
    admissionDate: '02/06/2024',
    dischargeDate: '02/06/2024',
  },
  {
    patientID: 'PAT-003',
    name: 'Michael Brown',
    age: 67,
    gender: 'Male',
    diagnosis: 'Diabetes Type II',
    status: 'admitted',
    doctor: 'Dr. Lee',
    department: 'Endocrinology',
    admissionDate: '10/01/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-004',
    name: 'Emily Davis',
    age: 54,
    gender: 'Female',
    diagnosis: 'Knee Replacement',
    status: 'discharged',
    doctor: 'Dr. Patel',
    department: 'Orthopedics',
    admissionDate: '22/11/2023',
    dischargeDate: '30/11/2023',
  },
  {
    patientID: 'PAT-005',
    name: 'Chris Wilson',
    age: 29,
    gender: 'Male',
    diagnosis: 'Migraine',
    status: 'discharged',
    doctor: 'Dr. Adams',
    department: 'Neurology',
    admissionDate: '08/02/2024',
    dischargeDate: '08/02/2024',
  },
  {
    patientID: 'PAT-006',
    name: 'Sophia Martinez',
    age: 40,
    gender: 'Female',
    diagnosis: 'Pneumonia',
    status: 'under-treatment',
    doctor: 'Dr. Taylor',
    department: 'Pulmonology',
    admissionDate: '12/03/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-007',
    name: 'David Clark',
    age: 51,
    gender: 'Male',
    diagnosis: 'Coronary Artery Disease',
    status: 'scheduled',
    doctor: 'Dr. White',
    department: 'Cardiology',
    admissionDate: '19/04/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-008',
    name: 'Olivia Harris',
    age: 27,
    gender: 'Female',
    diagnosis: 'Appendicitis',
    status: 'registered',
    doctor: 'Dr. Carter',
    department: 'General Surgery',
    admissionDate: '05/05/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-009',
    name: 'Daniel Lewis',
    age: 38,
    gender: 'Male',
    diagnosis: 'Back Pain',
    status: 'under-treatment',
    doctor: 'Dr. Evans',
    department: 'Orthopedics',
    admissionDate: '11/06/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-010',
    name: 'Grace Walker',
    age: 60,
    gender: 'Female',
    diagnosis: 'Stroke',
    status: 'admitted',
    doctor: 'Dr. Collins',
    department: 'Neurology',
    admissionDate: '18/06/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-011',
    name: 'James Young',
    age: 73,
    gender: 'Male',
    diagnosis: 'Chronic Kidney Disease',
    status: 'under-treatment',
    doctor: 'Dr. King',
    department: 'Nephrology',
    admissionDate: '20/07/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-012',
    name: 'Ava Scott',
    age: 19,
    gender: 'Female',
    diagnosis: 'Fractured Arm',
    status: 'scheduled',
    doctor: 'Dr. Adams',
    department: 'Orthopedics',
    admissionDate: '23/07/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-013',
    name: 'Ethan Hall',
    age: 34,
    gender: 'Male',
    diagnosis: 'Anxiety Disorder',
    status: 'registered',
    doctor: 'Dr. Turner',
    department: 'Psychiatry',
    admissionDate: '01/08/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-014',
    name: 'Mia Allen',
    age: 48,
    gender: 'Female',
    diagnosis: 'Breast Cancer',
    status: 'admitted',
    doctor: 'Dr. Green',
    department: 'Oncology',
    admissionDate: '03/08/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-015',
    name: 'William Wright',
    age: 36,
    gender: 'Male',
    diagnosis: 'Ulcer',
    status: 'discharged',
    doctor: 'Dr. Hill',
    department: 'Gastroenterology',
    admissionDate: '12/08/2024',
    dischargeDate: '15/08/2024',
  },
  {
    patientID: 'PAT-016',
    name: 'Isabella King',
    age: 42,
    gender: 'Female',
    diagnosis: 'Thyroid Disorder',
    status: 'under-treatment',
    doctor: 'Dr. Lee',
    department: 'Endocrinology',
    admissionDate: '14/08/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-017',
    name: 'Henry Lopez',
    age: 64,
    gender: 'Male',
    diagnosis: 'Lung Cancer',
    status: 'admitted',
    doctor: 'Dr. Perez',
    department: 'Oncology',
    admissionDate: '21/08/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-018',
    name: 'Charlotte Hill',
    age: 25,
    gender: 'Female',
    diagnosis: 'Gallstones',
    status: 'scheduled',
    doctor: 'Dr. Ward',
    department: 'General Surgery',
    admissionDate: '28/08/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-019',
    name: 'Benjamin Scott',
    age: 58,
    gender: 'Male',
    diagnosis: 'COPD',
    status: 'under-treatment',
    doctor: 'Dr. Reed',
    department: 'Pulmonology',
    admissionDate: '04/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-020',
    name: 'Amelia Adams',
    age: 33,
    gender: 'Female',
    diagnosis: 'Irritable Bowel Syndrome',
    status: 'registered',
    doctor: 'Dr. Torres',
    department: 'Gastroenterology',
    admissionDate: '06/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-021',
    name: 'Logan Perez',
    age: 47,
    gender: 'Male',
    diagnosis: 'Prostate Cancer',
    status: 'admitted',
    doctor: 'Dr. Mitchell',
    department: 'Oncology',
    admissionDate: '10/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-022',
    name: 'Ella White',
    age: 39,
    gender: 'Female',
    diagnosis: 'Seizure Disorder',
    status: 'discharged',
    doctor: 'Dr. Carter',
    department: 'Neurology',
    admissionDate: '15/09/2024',
    dischargeDate: '20/09/2024',
  },
  {
    patientID: 'PAT-023',
    name: 'Lucas Martinez',
    age: 30,
    gender: 'Male',
    diagnosis: 'ACL Tear',
    status: 'scheduled',
    doctor: 'Dr. Allen',
    department: 'Orthopedics',
    admissionDate: '17/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-024',
    name: 'Harper Green',
    age: 22,
    gender: 'Female',
    diagnosis: 'Skin Rash',
    status: 'registered',
    doctor: 'Dr. Scott',
    department: 'Dermatology',
    admissionDate: '20/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-025',
    name: 'Jackson Rivera',
    age: 55,
    gender: 'Male',
    diagnosis: 'Heart Failure',
    status: 'under-treatment',
    doctor: 'Dr. Roberts',
    department: 'Cardiology',
    admissionDate: '25/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-026',
    name: 'Scarlett Nelson',
    age: 49,
    gender: 'Female',
    diagnosis: 'Multiple Sclerosis',
    status: 'admitted',
    doctor: 'Dr. Baker',
    department: 'Neurology',
    admissionDate: '27/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-027',
    name: 'Matthew Carter',
    age: 68,
    gender: 'Male',
    diagnosis: 'Alzheimer’s Disease',
    status: 'under-treatment',
    doctor: 'Dr. Clark',
    department: 'Neurology',
    admissionDate: '29/09/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-028',
    name: 'Victoria Mitchell',
    age: 37,
    gender: 'Female',
    diagnosis: 'Rheumatoid Arthritis',
    status: 'scheduled',
    doctor: 'Dr. Hernandez',
    department: 'Rheumatology',
    admissionDate: '01/10/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-029',
    name: 'Andrew Gonzalez',
    age: 52,
    gender: 'Male',
    diagnosis: 'Cirrhosis',
    status: 'admitted',
    doctor: 'Dr. King',
    department: 'Gastroenterology',
    admissionDate: '05/10/2025',
    dischargeDate: null,
  },
  {
    patientID: 'PAT-030',
    name: 'Chloe Ramirez',
    age: 41,
    gender: 'Female',
    diagnosis: 'Depression',
    status: 'registered',
    doctor: 'Dr. Campbell',
    department: 'Psychiatry',
    admissionDate: '08/10/2025',
    dischargeDate: null,
  },
];

const resolvers = {
  Query: {
    patients: () => patients,
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });

export const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new SchemaLink({ schema }),
});
